name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 0"

# Declare default permissions as read only.
permissions: read-all

env:
  NODE_ENV: production
  NODE_VERSION: 17

jobs:

  test:
    runs-on: ubuntu-latest
    if: github.repository == 'flutter/website'
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "Beta channel"
            channel: beta
            experimental: true
          - name: "Stable channel"
            channel: stable
            experimental: false
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
      - name: Test
        run: make test
        env:
          TEST_TARGET_CHANNEL: ${{ matrix.channel }}
        continue-on-error: ${{ matrix.experimental }}

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'push'
      && github.ref == 'refs/heads/main'
      && github.repository == 'flutter/website'
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
        with:
          submodules: "recursive"
      - name: Install Node
        uses: actions/setup-node@2fddd8803e2f5c9604345a0b591c3020ee971a93
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install firebase tools
        run: npm ci
      - name: Update path
        run: echo "./node_modules/.bin/" >> $GITHUB_PATH
      - name: Build
        run: make build
        env:
          DISABLE_TESTS: 1
      - name: Deploy
        run: make deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_ALIAS: default
